version: "3.9"
services:
  db:
    image: postgres:16
    container_name: db
    ports:
      - 15432:5432
    networks:
      - compose-bridge
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
  app:
    build: .
    container_name: app
    environment:
      DB_URL: jdbc:postgresql://db:5432/${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      OPENCAGE_API_KEY: ${OPENCAGE_API_KEY}
    networks:
      - compose-bridge
    ports:
      - 8080:8080
networks:
  compose-bridge:
    driver: bridge
volumes:
  db_data: