ALTER TABLE donation ADD COLUMN status VARCHAR(20) DEFAULT 'CREATED' NOT NULL;
ALTER TABLE request ADD COLUMN stater VARCHAR(20) DEFAULT 'CREATED' NOT NULL;

UPDATE donation SET status = 'CREATED' WHERE status IS NULL;
